### PR TITLE
week 1 interview

### PR DESCRIPTION
**Pull request by indekkusu-era**
- Article Type: interviews
- Header: Team Insights: Post-Qualifiers Interview
- Subtitle: With the qualifiers concluded, every team is now preparing for the upcoming bracket stages. Let's see how the first seed Singapore, and the newborn team, Nicaragua are doing! Alongside with the Carbonara tips from Italy!
- Author(s): Arccat, TheFunk, Polytetral

### CODE REVIEW

**Comment by indekkusu-era** [comment]
(you can suggest the better article name and subtitle btw im out of ideas lol)

**Review by TheFunks — APPROVED** [review]
I'm gonna poison everyone with this carbonara recipe

**Review by polytetralhx — CHANGES_REQUESTED** [review]
line 37: change to "A new and fresh team has risen to the challenge of 4 Digit MWC! It always feels good to see new faces in this tournament. Team Nicaragua, how do you feel getting a spot in the Top 32?"

otherwise should be all good

**Review by polytetralhx — APPROVED** [review]
el gee tee em

**Comment by Leon1805** [comment]
Real

**Pull request merged**
